TASK_TYPE: inference_i2vgen_entrance
use_fp16: True
guide_scale: 9.0
use_fp16: True
chunk_size: 2
decoder_bs: 2
max_frames: 16
target_fps: 16      # FPS Conditions 
scale: 8
batch_size: 1
use_zero_infer: True 
# For important input
round: 4
seed: 0
data_root: workspace/test_imgs/test_img_01
# test_list_path: workspace/test_imgs/test_img_01.txt
test_list_path: workspace/test_imgs/test_img_02.txt
cap_dict_path: workspace/test_imgs/cap_dict_01.json
vldm_cfg: configs/i2vgen_xl_train.yaml
test_model: models/i2vgen_xl_person_00854500.pth
