TASK_TYPE: inference_text2video_entrance
use_fp16: True
guide_scale: 9.0
use_fp16: True
chunk_size: 2
decoder_bs: 2
max_frames: 16
target_fps: 16      # FPS Conditions, not encoding fps
scale: 8
batch_size: 1
use_zero_infer: True 
# For important input
round: 4
seed: 8888
test_list_path: data/text_img_for_t2v.txt
vldm_cfg: configs/t2v_train.yaml
test_model: workspace/model_bk/model_scope_0267000.pth
